"""Initial migration with all tables

Revision ID: 9c5fd66f51cc
Revises: 
Create Date: 2025-10-16 04:20:30.780243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5fd66f51cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webinars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('date_hosted', sa.DateTime(), nullable=True),
    sa.Column('offer_name', sa.String(length=255), nullable=True),
    sa.Column('offer_description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('deadline', sa.String(length=100), nullable=True),
    sa.Column('replay_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webinars_id'), 'webinars', ['id'], unique=False)
    op.create_table('attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webinar_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=False),
    sa.Column('attendance_percent', sa.Integer(), nullable=True),
    sa.Column('focus_percent', sa.Integer(), nullable=True),
    sa.Column('attendance_minutes', sa.Integer(), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('engagement_score', sa.Integer(), nullable=True),
    sa.Column('engagement_tier', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['webinar_id'], ['webinars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendees_email'), 'attendees', ['email'], unique=False)
    op.create_index(op.f('ix_attendees_id'), 'attendees', ['id'], unique=False)
    op.create_index(op.f('ix_attendees_webinar_id'), 'attendees', ['webinar_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendee_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_question', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_attendee_id'), 'chat_messages', ['attendee_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_table('generated_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendee_id', sa.Integer(), nullable=False),
    sa.Column('subject_line', sa.String(length=500), nullable=False),
    sa.Column('email_body_text', sa.Text(), nullable=False),
    sa.Column('email_body_html', sa.Text(), nullable=True),
    sa.Column('engagement_score', sa.Integer(), nullable=True),
    sa.Column('engagement_tier', sa.String(length=20), nullable=True),
    sa.Column('personalization_elements', sa.JSON(), nullable=True),
    sa.Column('user_edited', sa.Boolean(), nullable=False),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_emails_attendee_id'), 'generated_emails', ['attendee_id'], unique=True)
    op.create_index(op.f('ix_generated_emails_id'), 'generated_emails', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_emails_id'), table_name='generated_emails')
    op.drop_index(op.f('ix_generated_emails_attendee_id'), table_name='generated_emails')
    op.drop_table('generated_emails')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_attendee_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_attendees_webinar_id'), table_name='attendees')
    op.drop_index(op.f('ix_attendees_id'), table_name='attendees')
    op.drop_index(op.f('ix_attendees_email'), table_name='attendees')
    op.drop_table('attendees')
    op.drop_index(op.f('ix_webinars_id'), table_name='webinars')
    op.drop_table('webinars')
    # ### end Alembic commands ###
